name: Build and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies and Build
        run : |
          npm ci
          npm run build
      - name: List Files to Upload
        run: |
          echo "ðŸ“¦ Files to be uploaded:"
          find ./dist -type f
          ls package.json package-lock.json
    
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Service-API
          path: |
            package.json
            package-lock.json            
            ./dist

      - name: Build and Upload Summary
        run: |
          echo "### âœ… Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- Artifact: Service-API" >> $GITHUB_STEP_SUMMARY
          echo "- Files included:" >> $GITHUB_STEP_SUMMARY
          find ./dist -type f | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          echo "- package.json" >> $GITHUB_STEP_SUMMARY
          echo "- package-lock.json" >> $GITHUB_STEP_SUMMARY
      
        
      
    
